'use client';
import {useEffect,useMemo,useState} from 'react';
const qs=[
 {q:'昨夜はよく眠れた？',a:['よく眠れた','まあまあ','あまり眠れなかった']},
 {q:'今の気分はどう？',a:['😊 とてもいい','🙂 まあまあ','😐 普通','😔 少し沈んでいる','😣 かなりしんどい']},
 {q:'今日は忙しい？',a:['ゆっくり','普通','忙しい','かなり忙しい']},
 {q:'今日はどんな気分で過ごしたい？',a:['元気に','穏やかに','集中して','楽しく','静かに']},
 {q:'今、何か気になっていることはある？',a:['特になし','少しある','話してみたい']}
];
const suggestions={
 calm:{title:'今日は、自分のペースで。',text:'今のあなたには、小さく整える時間が合いそうです。',food:'温かいものを一品',color:'淡いブルー',action:'5分だけ外の空気を',rest:'3分だけ何もしない'},
 tired:{title:'今日は、余白をひとつ。',text:'少し疲れがありそう。全部を頑張らず、休めるところを作ってみよう。',food:'消化のよい温かいもの',color:'やわらかなグリーン',action:'肩をゆっくり回す',rest:'目を閉じて3分休む'},
 bright:{title:'いい流れを、大切に。',text:'今日は比較的気持ちよく始められそう。その感覚を急がず大切にしよう。',food:'好きなものを一品',color:'やさしいイエロー',action:'少し遠回りして歩く',rest:'好きな飲み物で一息'}
};
function Megu({mood='smile'}){return <div className={'megu '+mood} aria-label="芽ちゃん"><i/><b>{mood==='sleep'?'⌒':'•'}</b><b>{mood==='sleep'?'⌒':'•'}</b><span>{mood==='sad'?'︵':mood==='sleep'?'﹏':'‿'}</span></div>}
function classify(a){if((a[0]||'').includes('あまり')||(a[1]||'').includes('しんどい')||(a[2]||'').includes('かなり'))return 'tired';if((a[1]||'').includes('とてもいい'))return 'bright';return 'calm'}
export default function Page(){
 const [screen,setScreen]=useState('home'),[step,setStep]=useState(0),[ans,setAns]=useState([]),[records,setRecords]=useState([]),[memories,setMemories]=useState([]),[msg,setMsg]=useState(''),[notice,setNotice]=useState(true),[loaded,setLoaded]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{try{setRecords(JSON.parse(localStorage.getItem('kokoro-records')||'[]'));setMemories(JSON.parse(localStorage.getItem('kokoro-memories')||'[]'));setNotice(JSON.parse(localStorage.getItem('kokoro-notice')??'true'));const draft=JSON.parse(localStorage.getItem('kokoro-draft')||'null');if(draft&&Date.now()-draft.at<86400000){setAns(draft.ans||[]);setStep(draft.step||0)}}catch{}setLoaded(true)},[]);
 const today=useMemo(()=>new Date().toLocaleDateString('ja-JP'),[]); const latest=records[0];
 const goHome=()=>{setScreen('home');setStep(0);setAns([]);setSaved(false);localStorage.removeItem('kokoro-draft')};
 const startCheck=()=>{setSaved(false);const draft=JSON.parse(localStorage.getItem('kokoro-draft')||'null');if(draft&&Date.now()-draft.at<86400000&&(draft.ans||[]).length){setAns(draft.ans);setStep(draft.step);setScreen('check')}else{setStep(0);setAns([]);setScreen('check')}};
 const choose=(v)=>{const n=[...ans,v];setAns(n);if(step<4){const next=step+1;setStep(next);localStorage.setItem('kokoro-draft',JSON.stringify({ans:n,step:next,at:Date.now()}));return}const type=classify(n),r={date:today,mood:n[1],type,answers:n};const nr=[r,...records.filter(x=>x.date!==r.date)].slice(0,30);setRecords(nr);localStorage.setItem('kokoro-records',JSON.stringify(nr));localStorage.removeItem('kokoro-draft');setScreen('result')};
 const remember=()=>{if(!ans[4]||ans[4]==='特になし')return;const m={id:Date.now(),date:today,text:`今日、気になることが「${ans[4]}」だった`};const nm=[m,...memories].slice(0,20);setMemories(nm);setSaved(true);localStorage.setItem('kokoro-memories',JSON.stringify(nm))};
 const removeMemory=id=>{const nm=memories.filter(x=>x.id!==id);setMemories(nm);localStorage.setItem('kokoro-memories',JSON.stringify(nm))};
 if(!loaded)return <main><section className="hero"><Megu mood="sleep"/><p>芽ちゃんが準備しています…</p></section></main>;
 if(screen==='check')return <main><header>こころ日和 <em>{step+1}/5</em></header><section className="card chat"><Megu mood={step===1?'smile':'sleep'}/><div className="bubble"><h2>{qs[step].q}</h2><p>急がなくて大丈夫。今の気持ちに近いものを選んでね。</p></div>{qs[step].a.map(x=><button className="answer" key={x} onClick={()=>choose(x)}>{x}</button>)}</section><button className="back" onClick={goHome}>← ホームへ</button></main>;
 if(screen==='result'){const s=suggestions[classify(ans)];return <main><header>今日のあなた</header><section className="card center"><Megu mood={classify(ans)==='tired'?'sleep':'smile'}/><h2>{s.title}</h2><p>{s.text}</p><div className="grid"><div>🍚<b>食事</b><small>{s.food}</small></div><div>🫧<b>今日の色</b><small>{s.color}</small></div><div>🌿<b>行動</b><small>{s.action}</small></div><div>☕<b>休憩</b><small>{s.rest}</small></div></div><blockquote>全部できなくても大丈夫。ひとつ選べれば十分だよ。</blockquote>{ans[4]&&ans[4]!=='特になし'&&!memories.some(m=>m.date===today)&&!saved&&<button className="soft" onClick={remember}>🌱 今日の気がかりを覚えておく</button>}{saved&&<p className="saved">✓ 芽ちゃんが覚えました。設定からいつでも削除できます。</p>}<button onClick={goHome}>これでいこう</button></section></main>}
 if(screen==='records')return <main><header>気分の記録</header><section className="card"><h2>最近のこころ日和</h2>{records.length?records.map((r,i)=><div className="record" key={i}><span>{r.date}</span><b>{r.mood}</b></div>):<p>まだ記録はありません。今日から少しずつ残していこう。</p>}</section><button className="back" onClick={goHome}>← ホームへ</button></main>;
 if(screen==='memory')return <main><header>芽ちゃんの記憶</header><section className="card"><Megu/><h2>覚えていること</h2><p>あなたが「覚えておく」を選んだことだけ、ここに残ります。</p>{memories.length?memories.map(m=><div className="memory" key={m.id}><div><small>{m.date}</small><p>{m.text}</p></div><button onClick={()=>removeMemory(m.id)}>削除</button></div>):<p className="empty">まだありません。勝手に覚えることはしないよ。</p>}</section><button className="back" onClick={goHome}>← ホームへ</button></main>;
 if(screen==='settings')return <main><header>設定</header><section className="card"><h2>こころ日和の設定</h2><div className="setting"><div><b>やさしい通知</b><small>端末通知への接続は次の段階で行います</small></div><button className={notice?'toggle on':'toggle'} onClick={()=>{const n=!notice;setNotice(n);localStorage.setItem('kokoro-notice',JSON.stringify(n))}}>{notice?'ON':'OFF'}</button></div><button className="menu" onClick={()=>setScreen('memory')}>🌱 芽ちゃんの記憶 <span>›</span></button><div className="privacy">このMVPの気分・記憶は、この端末のブラウザ内だけに保存します。外部AIや課金サービスには送信しません。</div></section><button className="back" onClick={goHome}>← ホームへ</button></main>;
 if(screen==='talk')return <main><header>芽ちゃんとお話し</header><section className="card chat"><Megu mood={msg?'smile':'sleep'}/>{memories[0]&&<div className="memoryhint">🌱 覚えていること：{memories[0].text}</div>}<div className="bubble">なんでも話してね。うれしいこと、ちょっと疲れたこと。何でも聞くよ。</div>{msg&&<><div className="userbubble">{msg}</div><div className="bubble">そっか。話してくれてありがとう。今日は少しだけ自分にやさしくしてみようか。</div></>}<form className="input" onSubmit={e=>{e.preventDefault();const v=e.currentTarget.elements.message.value.trim();if(v){setMsg(v);e.currentTarget.reset()}}}><input name="message" maxLength="1000" placeholder="メッセージを入力…"/><button aria-label="送信">➤</button></form><small className="demo">※MVPでは固定応答です。外部AIには接続していません。</small></section><button className="back" onClick={goHome}>← ホームへ</button></main>;
 return <main><header>こころ日和 <i>🌱</i></header><section className="hero"><Megu mood={latest?.type==='tired'?'sleep':'smile'}/><h1>おはよう。</h1><p>{latest?.date===today?'今日はもう気持ちを聞かせてもらったね。':'今日の気分はどう？'}<br/>ここでは、急がなくていいよ。</p><div className="moods">😊　🙂　😐　😔　😣</div><button onClick={startCheck}>{latest?.date===today?'今日の気分を更新する':'今日のチェックイン'}</button></section><section className="card"><h3>今日の小さなおすすめ</h3><div className="grid"><div>🍚<b>食事</b></div><div>🫧<b>色</b></div><div>🌿<b>行動</b></div><div>☕<b>休憩</b></div></div><button className="soft" onClick={()=>setScreen('talk')}>💬 芽ちゃんと少し話す</button></section><nav><button onClick={()=>setScreen('home')}>⌂<small>ホーム</small></button><button onClick={()=>setScreen('records')}>♡<small>記録</small></button><button onClick={()=>setScreen('memory')}>🌱<small>相棒</small></button><button onClick={()=>setScreen('settings')}>⚙<small>設定</small></button></nav></main>
}
